---
# GitHub workflow file
name: Check links in markdown

on:
  schedule:
    - cron: "1 6 */3 * *"
  push:
    paths:
      [
        "**.md",
        ".github/config/md-link-check.json",
        ".github/config/md-links.yml",
      ]

  pull_request:
    paths:
      [
        "**.md",
        ".github/config/md-link-check.json",
        ".github/config/md-links.yml",
      ]

jobs:
  check-links:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: ".github/config/md-link-check.json"
          use-quiet-mode: "yes"
